name: regcm5
channels:
  - conda-forge
  - defaults
dependencies:
  - gfortran
  - mpi
  - nco
  - ncview
  - cdo
  - libnetcdf
  - netcdf-fortran
  # Jupyter dependencies
  - bash_kernel
  # required to decouple binder and repo
  - nbgitpuller
  # optional jupyterlab extensions (i.e. git) build dependencies
  - jupyterlab-git #==0.37.1
  - nodejs #==17.9.0
  - wheel #==0.37.1
  # Other
  - gh #==2.11.3
