name: regcm5
channels:
  - conda-forge
  - defaults
dependencies:
  - gfortran==12.1.0
  - openmpi
  - nco==5.1.0
  - ncview==2.1.8
  - cdo==2.0.5
  - libnetcdf==4.8.1
  - netcdf-fortran==4.6.0
  # Jupyter dependencies
  - bash_kernel==0.8.0
  # required to decouple binder and repo
  - nbgitpuller==1.1.0
  # optional jupyterlab extensions (i.e. git) build dependencies
  - jupyterlab-git==0.39.1
  # Other
  - gh==2.14.7
